server:
  port: 8080

spring:
  datasource:
    url: postgresql://localhost:5432/napRoute
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: postgres
