spring:
  profiles:
    active: ${environmentName}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  whitelisted-urls:
    - /user/login
    - /user/register
    - /health
  filter-urls:
    - /user/me
    - /geoTag
    - /favourites
