server:
  port: ${PORT}

spring:
  datasource:
    url: jdbc:postgresql://dpg-d1m0m66mcj7s73b1dj7g-a/naproute
    username: root
    password: 5S0dC8OQYXR0thJLr1ds6UjvOxYncQi0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: postgres
